version : '3'

services:
  mysql:
    image: mysql:latest
    container_name: booksservice_database
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: javacream
    ports: 
      - "3406:3306"
      - "34060:33060"  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: webfrontend
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8183:80
